CorrWeb/Controllers/GameListController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Web;
using System.Web.Http;
using CorrWeb.Models;
using System.Web.Mvc;

namespace CorrWeb.Controllers
{
    public class GameListController : Controller
    {
        public Dictionary<string, GameList> ListSet;
        GameList currentGameList;

        // GET api/GameList
        public IEnumerable<GameList> GetGameLists()
        {
            ListSet = InitListSet();
            return ListSet.Values;
        }
        private Dictionary<string, GameList> InitListSet()
        {
            Dictionary<string, GameList> outSet = new Dictionary<string, GameList>();
            // this is meaningless - no need for the crossuser set
            // this is a placeholder in case we want multiple sets per user
            return outSet;
        }

        // GET api/GameList/5
        public GameList GetGameList(string id)
        {
            return currentGameList = new GameList(id);  // ListSet[id];
        }

        public ActionResult GameChange(int listIndex, string eventIndex, int gameIndex)
        {
            ChessPosition.V2.Game thisGame = Models.GameList.GameListContext.FindGame(listIndex, eventIndex, gameIndex);

            ViewBag.listIndex = listIndex;
            ViewBag.eventIndex = eventIndex;
            ViewBag.gameIndex = gameIndex;
            ViewBag.positionIndex = (thisGame == null ? -1 : (thisGame.Tags["Result"] == "*" ? thisGame.Plies.Count-1 : 0));
            ViewBag.selectedPanel = 2;
            return View("~/Views/Home/Index.cshtml");
        }
        public ActionResult PositionChange(int listIndex, string eventIndex, int gameIndex, int posIndex)
        {
            ChessPosition.V2.Game thisGame = Models.GameList.GameListContext.FindGame(listIndex, eventIndex, gameIndex);

            ViewBag.listIndex = listIndex;
            ViewBag.eventIndex = eventIndex;
            ViewBag.gameIndex = gameIndex;
            ViewBag.positionIndex = posIndex;
            ViewBag.selectedPanel = 2;
            return View("~/Views/Home/Index.cshtml");
        }


        protected override void Dispose(bool disposing)
        {
            base.Dispose(disposing);
        }

    }
}

CorrWeb/Views/Shared/Partial/GameBoard.cshtml
@model CorrWeb.Models.GameList

@section HeadCustomStyleBlock {
    <style type="text/css">
        @@font-face {
            font-family: Chess-7;
            src: url(~/Fonts.Chess-7.ttf);
        }
    </style>
}

<div style="width: 100%; float: left;">
    @if (ViewBag != null && ViewBag.listIndex != null && ViewBag.eventIndex != null && ViewBag.gameIndex != null)
    {
        ViewBag.thisGame = Model.FindGame(ViewBag.listIndex, ViewBag.eventIndex, ViewBag.gameIndex);
    }
    @if (ViewBag.thisGame != null)
    {
        int prevPos = ViewBag.positionIndex - 1;
        int rewPos = ViewBag.positionIndex - 5;
        int ffPos = ViewBag.positionIndex + 5;
        int nextPos = ViewBag.positionIndex + 1;
        if (prevPos < 0)
        {
            prevPos = 0;
        }
        if (rewPos < 0)
        {
            rewPos = 0;
        }
        if (ffPos >= ViewBag.thisGame.Plies.Count)
        {
            ffPos = ViewBag.thisGame.Plies.Count - 1;
        }
        if (nextPos >= ViewBag.thisGame.Plies.Count)
        {
            nextPos = ViewBag.thisGame.Plies.Count - 1;
        }
        <p style="font-size: 65px; text-align: center; font-family: Chess-7; line-height: 100%; margin: -50px 0 0px 30px">
            @Model.GetPositionString(ViewBag.listIndex, ViewBag.eventIndex, ViewBag.gameIndex, ViewBag.positionIndex)
        </p>
        <p style="text-align: left; background: gray; color: #202020; clear: left;">
            @Html.ActionLink("|<", "PositionChange", "GameList", new { listIndex = ViewBag.listIndex, eventIndex = ViewBag.eventIndex, gameIndex = ViewBag.gameIndex, posIndex = 0 }, null) |
            @Html.ActionLink("<<", "PositionChange", "GameList", new { listIndex = ViewBag.listIndex, eventIndex = ViewBag.eventIndex, gameIndex = ViewBag.gameIndex, posIndex = rewPos, posDelta = -5 }, null) |
            @Html.ActionLink("<", "PositionChange", "GameList", new { listIndex = ViewBag.listIndex, eventIndex = ViewBag.eventIndex, gameIndex = ViewBag.gameIndex, posIndex = prevPos, posDelta = -1 }, null) |
            @Html.ActionLink(">", "PositionChange", "GameList", new { listIndex = ViewBag.listIndex, eventIndex = ViewBag.eventIndex, gameIndex = ViewBag.gameIndex, posIndex = nextPos, posDelta = 1 }, null) |
            @Html.ActionLink(">>", "PositionChange", "GameList", new { listIndex = ViewBag.listIndex, eventIndex = ViewBag.eventIndex, gameIndex = ViewBag.gameIndex, posIndex = ffPos, posDelta = 5 }, null) |
            @Html.ActionLink(">|", "PositionChange", "GameList", new { listIndex = ViewBag.listIndex, eventIndex = ViewBag.eventIndex, gameIndex = ViewBag.gameIndex, posIndex = ViewBag.thisGame.Plies.Count - 1, posDelta = 1000 }, null) |
            @Html.ActionLink("Delete", "Delete", new { /* id=Model.PrimaryKey */ })
            }
        </p>
    }
    @if (ViewBag.thisGame == null)
    { 
        <p>No game is currently selected...</p>
    }
</div>

CorrWeb/Views/Shared/Partial/GameListTree.cshtml
@model CorrWeb.Models.GameList

<div style="width: 100%; ">
    <p style="text-align: left; float: left">
        @Model.Count() games currently on file
    </p>
    <ul style="text-align: left; clear: left">
        <li>Games on Move</li>
        <ul>
            @foreach (string e in Model.onMoveGameList.Keys)
            {
                <li>@e</li>
                <ul>
                    @for(int i=0; i<Model.onMoveGameList[e].Count; i++)
                    {
                        ChessPosition.V2.Game g  = Model.onMoveGameList[e][i];
                        <li>
                            @Html.ActionLink(
                                g.Tags["White"] + "-" + g.Tags["Black"],
                                "GameChange", "GameList", 
                                new { listIndex=0, eventIndex=e, gameIndex=i }, null)
                        </li>
                    }
                </ul>
            }
        </ul>
        <li>Games Waiting</li>
        <ul>
            @foreach (string e in Model.waitingGameList.Keys)
            {
                <li>@e</li>
                <ul>
                    @for (int i = 0; i < Model.waitingGameList[e].Count; i++)
                    {
                        ChessPosition.V2.Game g = Model.waitingGameList[e][i];
                        <li>
                            @Html.ActionLink(
                                g.Tags["White"] + "-" + g.Tags["Black"],
                                "GameChange", "GameList", 
                                new { listIndex=1, eventIndex=e, gameIndex=i }, null)
                        </li>
                    }
                </ul>
            }
        </ul>
        <li>Games Completed</li>
        <ul>
            @foreach (string e in Model.completeGameList.Keys)
            {
                <li>@e</li>
                <ul>
                    @for (int i = 0; i < Model.completeGameList[e].Count; i++)
                    {
                        ChessPosition.V2.Game g = Model.completeGameList[e][i];
                        <li>
                            @Html.ActionLink(
                                g.Tags["White"] + "-" + g.Tags["Black"],
                                "GameChange", "Home", 
                                new { listIndex=2, eventIndex=e, gameIndex=i }, null)
                        </li>
                    }
                </ul>
            }
        </ul>
    </ul>

    @Html.ActionLink("New Game", "New", new { /* id=Model.PrimaryKey */ })
    </p>
</div>

CorrWeb/Views/Shared/Partial/GameTags.cshtml
@model CorrWeb.Models.GameList

<p style="width: 100%; text-align: left;">

    @if (ViewBag != null && ViewBag.listIndex != null && ViewBag.eventIndex != null && ViewBag.gameIndex != null)
    {
        ViewBag.thisGame = Model.FindGame(ViewBag.listIndex, ViewBag.eventIndex, ViewBag.gameIndex);
    }
    @if (ViewBag.thisGame != null)
    {
        <table style="width: 100%; text-align: left; float: left;">
            @foreach (string tag in ViewBag.thisGame.Tags.Keys)
            {
                <tr>
                    <td>@tag</td>
                    <td>@ViewBag.thisGame.Tags[tag]</td>
                </tr>
            }
        </table>
    }
    @if (ViewBag.thisGame == null)
    { 
        <p>No game is currently selected...</p>
    }
    <br />
    <br />
</p>

CorrWeb/Views/Shared/Partial/MoveListGrid.cshtml
@model CorrWeb.Models.GameList

@ViewBag.thisGame

<div style="width: 100%; float: left">
    @if (ViewBag != null && ViewBag.listIndex != null && ViewBag.eventIndex != null && ViewBag.gameIndex != null)
    {
        ViewBag.thisGame = Model.FindGame(ViewBag.listIndex, ViewBag.eventIndex, ViewBag.gameIndex);
    }
    @if (ViewBag.thisGame != null)
    {
        <p style="width: 100%; text-align: left; float: left">
            Will be the move list for the currently selected game
        </p>
    }
    @if (ViewBag.thisGame == null)
    { 
        <p>No game is currently selected...</p>
    }
</div>